routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
/*Route::get('/',  function(){
	return view('index');
});*/
// Route::get('qr-code', function () 
// {
// 	$file = public_path('qr.png');
//   	return QRCode::text('thusa')->setOutfile($file)->png();    
// });
Route::get('history', 'HomeController@qrcode');
Route::get('/', 'PagesController@index');
Route::get('/index', 'PagesController@index')->name('index');
Route::resource('edit-profil', 'UsersController');
Route::resource('kategori-jasa', 'KategorisController');
Route::resource('tambah-jasa', 'TambahJasaController');
Route::resource('pembayaran-jasa', 'PembayaranController');
Route::resource('kontak-kami', 'KontakKamiController');
Route::resource('isi-testimonial', 'TestimonialController');
Route::get('/detail-jasa/{id}', 'PagesController@detailJasa')->name('detail-jasa');
Route::get('/keranjang-anda', 'PagesController@cart');
Route::get('/produk', 'PagesController@produk');
Route::get('search', 'PagesController@search');
Route::get('/hasilPencarian', 'PagesController@hasilPencarian');
Route::get('/checkout', 'PagesController@checkout');
Route::get('/pembayaran', 'PagesController@pembayaran');
Route::get('/bahasa-inggris', 'HomeController@bahasainggris');
Route::get('/biologi', 'HomeController@biologi');
Route::get('/dokumentasi-acara', 'HomeController@dokumentasiacara');
Route::get('/foto-pernikahan', 'HomeController@fotopernikahan');
Route::get('/foto-ulang-tahun', 'HomeController@fotoulangtahun');
Route::get('/furniture', 'HomeController@furniture');
Route::get('/matematika', 'HomeController@matematika');
Route::get('/mail', 'HomeController@mail');
Route::get('/editprofile', 'HomeController@editprofile');
Route::get('/cart/{id}', 'PagesController@AddToCart');
Route::get('/remove/{id}', 'PagesController@remove');
Route::get('/kontakkami', 'PagesController@kontakkami');
Route::get('/privacy-policy', 'PagesController@privacy');
Route::get('/verify/{token}', 'VerifyController@verify')->name('verify');

/** ADMIN */
Route::prefix('admin')->group(function() {
	Route::resource('dashboard', 'AdminsController');
	Route::resource('daftar-jasa', 'DaftarJasasController');
	Route::resource('daftar-user', 'DaftarUsersController');
	Route::resource('daftar-order', 'DaftarOrdersController');
	Route::resource('daftar-bukti-pembayaran', 'DaftarPembayaransController');
});

resources/views/admin/daftar-bukti-pembayaran.blade.php
@extends('layouts.layout-admin')
@section('Title')
	Jasaku ID | Admin | Daftar Bukti Pembayaran
@endsection
@section('content-admin')
<div id="page-wrapper">
    <div class="row" style="margin-top: 30px;">
        <div class="col-lg-12">
            <h1 class="page-header">Daftar Bukti Pembayaran</h1>
        </div>
        <!-- /.col-lg-12 -->        
    </div>
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Daftar Bukti Pembayaran
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Nomor</th>
                                <th>Nomor Pembayaran</th>
                                <th>Total Pembayaran</th>
                                <th>Nama Pemesan</th>
                                <th>Nama Pemilik Rekining</th>
                                <th>Nomor Rekening</th>
                                <th>Bukti Pembayaran</th>
                                <th>Waktu</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        
                        <tbody>
                            @foreach($pembayaran as $key => $pembayaran)
                            <tr class="odd gradeX">
                                <td>{{ $key+1 }}</td>
                                <td>{{ $pembayaran->nomor_pembayaran }}</td>
                                <td>{{ $pembayaran->jasa_yang_disewa }}</td>
                                <td>{{ $pembayaran->nama_pemesan }}</td>
                                <td>{{ $pembayaran->nama_pemilik_rekening }}</td>
                                <td>{{ $pembayaran->nomor_rekening }}</td>
                                <td><img src="{{ asset('images/Pembayaran-user/'.$pembayaran->bukti_pembayaran) }}" style="width: 500px; height: 150px;" class="img-responsive" /></td>
                                <td>Rp. {{ number_format($pembayaran->total_pembayaran, 2) }}</td>
                                <td>
                                    <!-- <form action="#" method="POST">
                                        {{ csrf_field() }} -->
                                        <input type="submit" value="Konfirmasi" class="btn btn-primary" name="submit"/>
                                    <!-- </form> -->
                                </td>
                            </tr>
                            @endforeach
                        </tbody>                        
                    </table>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>
@endsection

resources/views/admin/daftar-jasa.blade.php
@extends('layouts.layout-admin')
@section('Title')
	Jasaku ID | Admin | Daftar Jasa
@endsection
@section('content-admin')
<div id="page-wrapper">
    <div class="row" style="margin-top: 30px;">
        <div class="col-lg-12">
            <h1 class="page-header">Daftar Jasa</h1>
        </div>
        <!-- /.col-lg-12 -->        
    </div>
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Daftar Jasa
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Nomor</th>
                                <th>Nama</th>
                                <th>Deskripsi</th>
                                <th>Gambar</th>
                                <th>Harga</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        
                        <tbody>
                            @foreach($jasa as $key => $jasa)
                            <tr class="odd gradeX">
                                <td>{{ $key+1 }}</td>
                                <td>{{ $jasa->nama_jasa }}</td>
                                <td>{{ $jasa->deskripsi }}</td>
                                <td><img src="{{ asset('images/Jasa-user/'.$jasa->gambar_jasa) }}" style="width: 500px; height: 150px;" class="img-responsive" /></td>
                                <td class="center">Rp {{ number_format($jasa->harga_jasa, 2) }}</td>
                                <td>
                                    <form action="{{ route('daftar-jasa.destroy', $jasa->id) }}" method="POST">
                                        {{ method_field("DELETE") }}
                                        {{ csrf_field() }}
                                        <input type="submit" value="Hapus" class="btn btn-primary" name="submit"/>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>                        
                    </table>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>
@ensection

resources/views/admin/daftar-oder.blade.php
@extends('layouts.layout-admin')
@section('Title')
	Jasaku ID | Admin
@endsection
@section('content-admin')
<div id="page-wrapper">
    <div class="row" style="margin-top: 30px;">
        <div class="col-lg-12">
            <h1 class="page-header">Daftar Order</h1>
        </div>
        <!-- /.col-lg-12 -->        
    </div>
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Daftar Order
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Nomor</th>
                                <th>Nama</th>
                                <th>Email</th>
                                <th>Nama Jasa</th>
                                <th>Sub Total</th>
                                <th>Grand Total</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        
                        <tbody>
                            <tr class="odd gradeX">
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td>
                                    <!-- <form action="#" method="POST">
                                        {{ method_field("DELETE") }}
                                        {{ csrf_field() }} -->
                                        <input type="submit" value="Batalkan" class="btn btn-primary" name="submit"/>
                                    <!-- </form> -->
                                </td>
                            </tr>
                        </tbody>                        
                    </table>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>
@endsection

resources/views/admin/daftar-user.blade.php
@extends('layouts.layout-admin')
@section('Title')
	Jasaku ID | Admin
@endsection
@section('content-admin')
<div id="page-wrapper">
    <div class="row" style="margin-top: 30px;">
        <div class="col-lg-12">
            <h1 class="page-header">Daftar User</h1>
        </div>
        <!-- /.col-lg-12 -->        
    </div>
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Daftar User
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Nomor</th>
                                <th>Username</th>
                                <th>Nama</th>
                                <th>Email</th>
                                <th>Status</th>
                                <th>No. Handphone</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        
                        <tbody>
                            @foreach($user as $key => $user)
                            <tr class="odd gradeX">
                                <td>{{ $key+1 }}</td>
                                <td>{{ $user->username }}</td>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->email }}</td>
                                <td>{{ $user->status }}</td>
                                <td>{{ $user->no_handphone }}</td>
                                <td>
                                    <form action="{{ route('daftar-user.destroy', $user->id) }}" method="POST">
                                        {{ method_field("DELETE") }}
                                        {{ csrf_field() }}
                                        <input type="submit" value="Hapus" class="btn btn-primary" name="submit"/>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>                        
                    </table>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>
@endsection

resources/views/admin/dashboard.blade.php
@extends('layouts.layout-admin')
@section('Title')
	Jasaku ID | Admin
@endsection
@section('content-admin')
<div id="wrapper">
        <div id="page-wrapper">
            <div class="row" style="margin-top: 30px;">
                <div class="col-lg-12">
                    <h4 class="page-header">Selamat Datang, {{Auth::user()->name}} </h4>
                    <h5 class="page-header" style="text-transform: capitalize;">Anda Login Sebagai : {{ Auth::user()->status }}</h5>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-comments fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">{{$jasa}}</div>
                                    <div>Daftar Jasa</div>
                                </div>
                            </div>
                        </div>
                        <a href="{{ route('daftar-jasa.index') }}">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-tasks fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">{{$user}}</div>
                                    <div>Daftar User</div>
                                </div>
                            </div>
                        </div>
                        <a href="{{ route('daftar-user.index') }}">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-shopping-cart fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">0</div>
                                    <div>Daftar Orders</div>
                                </div>
                            </div>
                        </div>
                        <a href="{{ route('daftar-order.index') }}">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-support fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">{{$pembayaran}}</div>
                                    <div>Daftar Bukti Pembayaran</div>
                                </div>
                            </div>
                        </div>
                        <a href="{{ route('daftar-bukti-pembayaran.index') }}">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-wrapper -->

    </div>
@endsection