routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
/*Route::get('/',  function(){
	return view('index');
});*/
// Route::get('qr-code', function () 
// {
// 	$file = public_path('qr.png');
//   	return QRCode::text('thusa')->setOutfile($file)->png();    
// });
Route::get('history', 'HomeController@qrcode');
Route::get('/', 'PagesController@index');
Route::get('/index', 'PagesController@index')->name('index');
Route::resource('edit-profil', 'UsersController');
Route::resource('kategori-jasa', 'KategorisController');
Route::resource('tambah-jasa', 'TambahJasaController');
Route::resource('pembayaran-jasa', 'PembayaranController');
Route::resource('kontak-kami', 'KontakKamiController');
Route::resource('isi-testimonial', 'TestimonialController');
Route::get('/detail-jasa/{id}', 'PagesController@detailJasa')->name('detail-jasa');
Route::get('/keranjang-anda', 'PagesController@cart');
Route::get('/produk', 'PagesController@produk');
Route::get('search', 'PagesController@search');
Route::get('/hasilPencarian', 'PagesController@hasilPencarian');
Route::get('/checkout', 'PagesController@checkout');
Route::get('/pembayaran', 'PagesController@pembayaran');
Route::get('/bahasa-inggris', 'HomeController@bahasainggris');
Route::get('/biologi', 'HomeController@biologi');
Route::get('/dokumentasi-acara', 'HomeController@dokumentasiacara');
Route::get('/foto-pernikahan', 'HomeController@fotopernikahan');
Route::get('/foto-ulang-tahun', 'HomeController@fotoulangtahun');
Route::get('/furniture', 'HomeController@furniture');
Route::get('/matematika', 'HomeController@matematika');
Route::get('/mail', 'HomeController@mail');
Route::get('/editprofile', 'HomeController@editprofile');
Route::get('/cart/{id}', 'PagesController@AddToCart');
Route::get('/remove/{id}', 'PagesController@remove');
Route::get('/kontakkami', 'PagesController@kontakkami');
Route::get('/privacy-policy', 'PagesController@privacy');
Route::get('/verify/{token}', 'VerifyController@verify')->name('verify');

/** ADMIN */
Route::prefix('admin')->group(function() {
	Route::resource('dashboard', 'AdminsController');
	Route::resource('daftar-jasa', 'DaftarJasasController');
	Route::resource('daftar-user', 'DaftarUsersController');
	Route::resource('daftar-order', 'DaftarOrdersController');
	Route::resource('daftar-bukti-pembayaran', 'DaftarPembayaransController');
});

resources/views/jasaku/checkout.blade.php
@extends('layouts.layout')
@section('Title')
	Jasaku ID | Checkout
@endsection
@section('Content')

<!-- breadcrumbs -->
<div class="breadcrumbs">
	<div class="container">
		<ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
			<li><a href="{{ url('index') }}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Beranda</a></li>
			<li><a href="{{ url('/keranjang-anda') }}">Keranjang Anda</a></li>
			<li class="active">Checkout</li>
		</ol>
	</div>
</div>
<!-- //breadcrumbs -->	
@if(Session::has('cart'))
<div class="login-form-grids">
	<div class="row">
		<h3 class="animated wow slideInLeft" data-wow-delay=".5s">Daftar Jasa Yang Dipilih</h3>
		<br><br>
			@foreach($jasas as $jasa)
				<div class="col-md-4">
				<img src="{{ asset('images/Jasa-user/'.$jasa['item']['gambar_jasa']) }}" style="width: 80%; height: 100%;">
				</div>
				<strong>{{ $jasa['item']['nama_jasa'] }}</strong>
				<br>
				<span class="badge">{{ $jasa['qty'] }}</span> x
				<span class="label label-success">Rp. {{ number_format($jasa['harga_jasa'], 2) }}</span>
				<hr>
			@endforeach
	</div>
	
	<div class="row">
		<hr>
		<strong>Total: Rp. {{ number_format($totalPrice, 2) }}</strong>			
		<hr>
	</div>
	
	<div class="row">
		<a href="{{ url('/keranjang-anda') }}" class="btn btn-primary animated wow slideInLeft" role="button">Kembali ke Keranjang Anda</a>
		<br><br>
		<a href="{{ route('pembayaran-jasa.index') }}" class="btn btn-success animated wow slideInLeft" role="button">Konfirmasi Pembayaran</a>
	</div>
</div>
@endif
<br><br>
@endsection

resources/views/jasaku/detail-jasa.blade.php
@extends('layouts.layout')
@section('Title')
	Jasaku ID | Fotografi dan Videografi | Dokumentasi Acara
@endsection
@section('Content')
<!-- breadcrumbs -->
	<div class="breadcrumbs">
		<div class="container">
			<ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
				<li><a href="{{ url('index') }}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Beranda</a></li>
				@foreach($jasaYangSesuai as $detail)
				<li class=""><a href="{{ url('kategori-jasa/'.$detail->nama_kategori)}}">{{ $detail->nama_kategori }}</a></li>
				<li class="">{{ $detail->nama_jasa }}</li>
				@endforeach
				
			</ol>
		</div>
	</div>
	@foreach($detailJasa as $detail)
	<div class="new-collections">
		<div class="container">
			<div class="col-md-20 products-right">
				<div class="products-right-grid">
					<div class="products-right-grids-position animated wow slideInRight inline" data-wow-delay=".5s">
						<img src="{{ asset('images/Jasa-user/'.$detail->gambar_jasa) }}" alt=" " class="img-responsive" />
						<div class="products-right-grids-position1">
							<h4>Jasa Terbaru 2018</h4>
							<p>Pilih jasa yang kamu inginkan disini, dengan harga yang murah dan juga pihak yang terpercaya jadikan kebutuhanmu menjadi lebih mudah dengan Jasaku ID.</p>
						</div>
					</div>
				</div>
				
				<ol class="breadcrumb breadcrumb1 animated wow slideInLeft">
					<div class="col-md-3 new-collections-grid">
						<div class="new-collections-grid1 new-collections-grid1-image-width animated wow slideInUp" data-wow-delay=".5s" >
							<div class="new-collections-grid1-image">
								<a href="single.html" class="product-image"><img src="{{ asset('images/Jasa-user/'.$detail->gambar_jasa) }}" alt=" " class="img-responsive"></a>
								<div class="new-collections-grid1-image-pos">
									<a href="#">Quick View</a>
								</div>
							</div>
							
							<h4><a href="#">{{$detail->nama_jasa}}</a></h4>
							<p>{{$detail->deskripsi}}</p>
							<h4 class="fontjasa">Rp {{ number_format($detail->harga_jasa, 2) }}</h4>
							<div class="simpleCart_shelfItem products-right-grid1-add-cart">
								<p><a class="item_add mid" href="{{ url('/cart/'.$detail->id) }}">Pilih </a></p>
							</div>
						</div>
					</div>
				</ol>
				<div class="clearfix"> </div>
				@endforeach
				<nav class="numbering animated wow slideInRight" data-wow-delay=".5s">
				  <ul class="pagination paging">
					<li>
					  <a href="#" aria-label="Previous">
						<span aria-hidden="true">&laquo;</span>
					  </a>
					</li>
					<li class="active"><a href="#">1<span class="sr-only">(current)</span></a></li>
					<li><a href="#">2</a></li>
					<li><a href="#">3</a></li>
					<li><a href="#">4</a></li>
					<li><a href="#">5</a></li>
					<li>
					  <a href="#" aria-label="Next">
						<span aria-hidden="true">&raquo;</span>
					  </a>
					</li>
				  </ul>
				</nav>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
<!-- //breadcrumbs -->
@endsection

resources/views/jasaku/editprofile.blade.php
@extends('layouts.layout-editprofil')
@section('Title1')
    Jasaku ID | Edit Profil
@endsection
@section('Content-Form')
<!-- register -->
    <div class="register">
        <div class="container">
            <h3 class="animated wow zoomIn" data-wow-delay=".5s">Edit Profil</h3>
            <div class="login-form-grids">
                <h5 class="animated wow slideInUp" data-wow-delay=".5s">Informasi Profil</h5>
                <form class="animated wow slideInUp" data-wow-delay=".5s" method="POST" action="{{ route('edit-profil.update', $profil->id) }}">
                 {{ csrf_field() }}
                 {{ method_field("PUT") }} 
                    <input type="text" placeholder="Nama Lengkap" required autofocus class="form-group{{ $errors->has('name') ? ' has-error' : '' }}" id="name" class="form-control" name="name" value="{{ $profil->name }}">
                        @if ($errors->has('name'))
                            <span class="help-block">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                        @endif

                    <input type="text" placeholder="Username" required autofocus class="form-group{{ $errors->has('username') ? ' has-error' : '' }}" id="username" class="form-control" name="username" value="{{ $profil->username }}">
                        @if ($errors->has('username'))
                            <span class="help-block">
                                <strong>{{ $errors->first('username') }}</strong>
                            </span>
                        @endif

                    <input type="email" placeholder="Alamat Email" class="form-group{{ $errors->has('email') ? ' has-error' : '' }}"  id="email" name="email" required value="{{ $profil->email }}">
                        @if ($errors->has('email'))
                            <span class="help-block">
                                <strong>{{ $errors->first('email') }}</strong>
                            </span>
                        @endif

                    <input type="text" placeholder="Nomor Handphone" class="form-group{{ $errors->has('nomor handphone') ? ' has-error' : '' }}"  id="no_handphone" name="no_handphone" value="{{ $profil->no_handphone }}" required>
                    @if ($errors->has('no_handphone'))
                        <span class="help-block">
                            <strong>{{ $errors->first('no_handphone') }}</strong>
                        </span>
                    @endif

                    <input type="submit" class="btn btn-primary" value="Simpan">
                </form>
              <!--   <input type="submit" class="btn btn-primary" value="Ganti Password" onclick="window.location.href='{{ url('index') }}'"> -->
            </div>
        </div>
    </div>
<!-- //register -->
@endsection

resources/views/jasaku/history-testimonial.blade.php
@extends('layouts.layout')
@section('Title')
	Jasaku ID | History Testimonial
@endsection
@section('Content')

<!-- breadcrumbs -->
<div class="breadcrumbs">
	<div class="container">
		<ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
			<li><a href="{{ url('index') }}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Beranda</a></li>
			<li><a href="{{ route('isi-testimonial.index') }}"></span>Isi Testimonial</a></li>
			<li class="active">History Testimonial</li>
		</ol>
	</div>
</div>
<!-- //breadcrumbs -->	
<div class="checkout">
	<div class="container">
		<?php $no=0 ?>
		<div class="checkout-right animated wow slideInUp" data-wow-delay=".5s">
			<div style="overflow-x:auto;" class="table-responsive">
				<table class="table table-striped table-bordered">
					<thead>
						<tr class="rem1">
							<th>No.</th>
							<th>Nama</th>
							<th>E-mail</th>	
							<th>Alamat</th>
							<th>Rating</th>
							<th>Judul Testi</th>
							<th>Pesan Testi</th>
							<th>Tanggal Publish</th>
						</tr>
					</thead>
					@foreach($testi as $testimonial)
					<tr class="rem1">
						<?php $no+=1 ?>
						<td class="invert">{{ $no }}</td>
						<td class="invert">{{ $testimonial->nama }}</td>
						<td class="invert">{{ $testimonial->email }}</td>
						<td class="invert">{{ $testimonial->alamat }}</td>
						<td class="invert">{{ $testimonial->rating }}</td>
						<td class="invert">{{ $testimonial->judul_testi }}</td>
						<td class="invert">{{ $testimonial->pesan_testi }}</td>
						<td class="invert">{{ $testimonial->created_at }}</td>

					</tr>
					@endforeach
				</table>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/jasaku/kategori-jasa.blade.php
@extends('layouts.layout')
@section('Title')
	Jasaku ID | Fotografi dan Videografi | Dokumentasi Acara
@endsection
@section('Content')
<!-- breadcrumbs -->
	<div class="breadcrumbs">
		<div class="container">
			<ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
				<li><a href="{{ url('index') }}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Beranda</a></li>
				@foreach($kategoriBerdasarkanId->take(1) as $detail)
				<li class="">{{ $detail->nama_kategori }}</li>
				@endforeach
			</ol>
		</div>
	</div>
<!-- //breadcrumbs -->
	
	<div class="new-collections">
		<div class="container">
			<div class="col-md-20 products-right">
				<!-- collections -->
				<div class="container">
					@foreach($kategoriBerdasarkanId as $detail)
						<ol class="breadcrumb breadcrumb1 animated wow slideInLeft">
							<div class="col-md-3 new-collections-grid">
								<div class="new-collections-grid1 new-collections-grid1-image-width animated wow slideInUp" data-wow-delay=".5s" >
									<div class="new-collections-grid1-image">
										<a href="single.html" class="product-image"><img src="{{ asset('images/Jasa-user/'.$detail->gambar_jasa) }}" alt=" " class="img-responsive"></a>
										<div class="new-collections-grid1-image-pos">
											<a href="#">Quick View</a>
										</div>
									</div>
									
									<h4><a href="#">{{$detail->nama_jasa}}</a></h4>
									<p>{{$detail->deskripsi}}</p>
									<h4 class="fontjasa">Rp {{ number_format($detail->harga_jasa, 2) }}</h4>
									<div class="simpleCart_shelfItem products-right-grid1-add-cart">
										<p><a class="item_add mid" href="{{ url('/cart/'.$detail->id_jasa) }}">Pilih </a></p>
									</div>
								</div>
								<div class="clearfix"> </div>
							</div>
						</ol>
					@endforeach
				</div>
				<!-- //collections -->
				<!-- menuslide -->
				<nav class="numbering animated wow slideInRight" data-wow-delay=".5s">
				  <ul class="pagination paging">
					<li>
					  <a href="#" aria-label="Previous">
						<span aria-hidden="true">&laquo;</span>
					  </a>
					</li>
					<li class="active"><a href="#">1<span class="sr-only">(current)</span></a></li>
					<li><a href="#">2</a></li>
					<li><a href="#">3</a></li>
					<li><a href="#">4</a></li>
					<li><a href="#">5</a></li>
					<li>
					  <a href="#" aria-label="Next">
						<span aria-hidden="true">&raquo;</span>
					  </a>
					</li>
				  </ul>
				</nav>
				<!-- //menuslide -->
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
@endsection

resources/views/jasaku/kontakkami.blade.php
@extends('layouts.layout')
@section('Title')
	Jasaku ID | Kontak Kami
@endsection
@section('Content')
<!-- breadcrumbs -->
	<div class="breadcrumbs">
		<div class="container">
			<ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
				<li><a href="index.html"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Beranda</a></li>
				<li class="active">Kontak Kami</li>
			</ol>
		</div>
	</div>
<!-- //breadcrumbs -->
<!-- mail -->
	<form method="POST" action="{{ route('kontak-kami.store') }}">
		{{ csrf_field() }}
		<div class="mail animated wow zoomIn" data-wow-delay=".5s">
		<div class="container">
			<h2 style="font-size: 48px;" class="mid">Kontak Kami</h2>
			<hr>
			<p class="est">Bila menemui masalah dalam penggunaan <b>JasakuID</b>, mohon kirimkan kritik dan saran dengan menggunakan format dibawah ini. Kritik dan saran yang anda kirimkan akan membantu kami dalam pengembangan <b>JasakuID</b> menjadi lebih baik. </p>
			<div class="mail-grids">
				<div class="col-md-8 mail-grid-left animated wow slideInLeft" data-wow-delay=".5s">
					<form>
						<input type="text" id="nama" name="nama" required="" placeholder="Nama">
						<input type="email" id="email" name="email" required="" placeholder="Email">
						<input type="text" id="subject" name="subject" required=""placeholder="Subject">
						<textarea type="text" id="pesan" name="pesan" required="" placeholder="Pesan Anda"></textarea>
						<input type="submit" value="Kirim Pesan" >
					</form>
				</div>
				<div class="col-md-4 mail-grid-right animated wow slideInRight" data-wow-delay=".5s">
					<div class="mail-grid-right1">
						<img src="images/logo_tab.png" alt=" " class="img-responsive" />
						<h4> Customer Service</h4>
						<ul class="phone-mail">
							<li><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i>Telp: 081990102911</li>
							<li><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i>Email: <a href="mailto:jasakuid@gmail.com">jasakuid@gmail.com</a></li>
						</ul>
						<ul class="social-icons">
							<li><a href="#" class="facebook"></a></li>
							<li><a href="#" class="twitter"></a></li>
							<li><a href="#" class="g"></a></li>
							<li><a href="http://www.instagram.com/jasakuid" class="instagram"></a></li>
						</ul>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
		</div>
	</form>
<!-- //mail -->
@endsection

resources/views/jasaku/pembayaran.blade.php
@extends('layouts.layout')
@section('Title')
	Jasaku ID | Konfirmasi Pembayaran
@endsection
@section('Content')

<!-- breadcrumbs -->
<div class="breadcrumbs">
	<div class="container">
		<ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
			<li><a href="{{ url('index') }}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Beranda</a></li>
			<li><a href="{{ url('/keranjang-anda') }}">Keranjang Anda</a></li>
			<li><a href="{{ url('/checkout') }}">Checkout</a></li>
			<li class="active">Konfirmasi Pembayaran</li>
		</ol>
	</div>
</div>
<!-- //breadcrumbs -->	
@if(Session::has('cart'))
<div class="row">
	<div class="col-sm-6 col-md-6 col-md-offset-3 col-sm-offset-3">
		<br><br>
		<div class="col-xs-12">
			<div class="form-group">
				<h3 class="animated wow slideInLeft mid" data-wow-delay=".5s">Konfirmasi Pembayaran</h3>
			</div>
		</div>
		<form enctype="multipart/form-data" method="POST" action="{{ route('pembayaran-jasa.store') }}" id="pembayaran">
			{{ csrf_field() }}
			<div class="col-xs-12">
				<div class="form-group">
					<strong style="color: red" name="total_pembayaran">Nomor Pembayaran: {{ $dateNow.$randomNum.$randomString }}</strong>
				</div>
			</div>
			<div class="col-xs-12">
				<div class="form-group">
					<strong style="color: red" name="total_pembayaran">Total Pembayaran: Rp. {{ number_format($totalPrice, 2) }}</strong>
				</div>
			</div>
			<br>
			<!-- Pembayaran@tHusA-->
			<div class="col-xs-12">
				<div class="form-group">
					<p>Nama Pemesan: </p>
					<input type="text" placeholder="Lionel Messi" required autofocus id="nama_pemesan" class="form-control" name="nama_pemesan">
				</div>
			</div>
			<div class="col-xs-12">
				<div class="form-group">
					<p>Alamat: </p>
					<input type="textarea" placeholder="659 s soto street los angeles ca 110030789580" required autofocus id="alamat" class="form-control" name="alamat">
				</div>
			</div>
			<div class="col-xs-6">
				<div class="form-group">
					<p>Nama Pemilik Rekening: </p>
					<input type="text" placeholder="A/N Lionel Messi" required autofocus id="nama_pemilik_rekening" class="form-control" name="nama_pemilik_rekening">		
				</div>
			</div>
			<div class="col-xs-6">
				<div class="form-group">
					<p>No. Rekening: </p>
					<input type="text" placeholder="Masukkan digit angka rekening anda" required autofocus id="nomor_rekening" class="form-control" name="nomor_rekening">
				</div>
			</div>
			<div class="col-xs-12">
				<div class="form-group">
	                <div class="animated wow zoomIn">
	                <p class="animated wow slideInUp" data-wow-delay=".5s">Masukkan Bukti Pembayaran:</p><br>
	                <input type="file" class="form-control-file" id="bukti_pembayaran" name="bukti_pembayaran">
	                <span class="help-block">
	                    <strong></strong>
	                </span>
	                </div>
	                <hr>
	                <div class="form-group">
						<strong style="color: red">HARAP DI PERHATIKAN.</strong>
						<p>Transfer ke Nomor Rekening: 13451148819293</p>
						<p>Jenis Bank: BCA</p>
						<p>A/N: John Wick</p>
					</div>
	                <hr>
				</div>
			</div>
			<div class="col-xs-12">
				<div class="form-group">
					<input type="submit" name="" class="btn btn-success" value="Confirm">
				</div>
			</div>
		</form>
	</div>
</div>
@endif
<br><br>
@endsection

resources/views/jasaku/tambah-jasa.blade.php
@extends('layouts.layout-editprofil')
@section('Title1')
    Jasaku ID | Tambah Jasa
@endsection
@section('Content-Form')

<!-- breadcrumbs -->
<div class="breadcrumbs">
    <div class="container">
        <ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
            <li><a href="{{ url('index') }}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Beranda</a></li>
            <li class="active">Tambah Jasa</li>
        </ol>
    </div>
</div>
<!-- //breadcrumbs -->
<!-- register -->
    <div class="register">
        <div class="container">
            <h3 class="animated wow zoomIn" data-wow-delay=".5s">Tambahkan Jasa</h3>
            <div class="login-form-grids">
                <h5 class="animated wow slideInUp" data-wow-delay=".5s">Informasi Jasa yang Dibutuhkan</h5>
                <form enctype="multipart/form-data" class="animated wow slideInUp" data-wow-delay=".5s" method="POST" action="{{ route('tambah-jasa.store') }}">
                 {{ csrf_field() }}
                     <div class="form-group has-feedback {{ $errors->has('user_kategori') ? ' has-error' : '' }}">
                        <select name="user_kategori" id="user_kategori" class="form-control required_mahasiswa" required placeholder="Kategori Jasa">
                            @foreach($kategori as $kategoris) 
                            <option value="{{$kategoris->id}}" class="yes">{{$kategoris->nama}}</option>
                            @endforeach
                        </select>
                    </div>
                    <input type="text" placeholder="Nama Jasa" required autofocus id="nama_jasa" class="form-control" name="nama_jasa" value="">
                            <span class="help-block">
                                <strong></strong>
                            </span>
                    <textarea placeholder="Deskripsi" rows="5" id="deskripsi" class="form-control" name="deskripsi"></textarea>
                            <span class="help-block">
                                <strong></strong>
                            </span>
                    <hr class="line-tambah-jasa">
                    <fieldset class="container">
                        <div class="animated wow zoomIn">
                        <h5 class="animated wow slideInUp" data-wow-delay=".5s">Masukkan Gambar:</h5>
                        <input type="file" class="form-control-file" id="gambar_jasa" name="gambar_jasa">
                        <span class="help-block">
                            <strong></strong>
                        </span>
                        </div>
                    </fieldset>
                    <hr class="line-tambah-jasa">
                    <input type="text" placeholder="Harga Jasa" required autofocus class="" id="harga_jasa" class="form-control" name="harga_jasa" value="" data-affixes-stay="true" data-prefix="Rp. " data-thousands="," data-decimal=".">
                    <input type="submit" class="btn btn-primary" value="Simpan">
                </form>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $('input[id="none"]').on('change', function () {
            if (this.checked) {
              $('.addcategory').hide();     
            }
        });

            $('input[class="yes"]').on('change', function () {
            if (this.checked) {
              $('.addcategory').show();     
            }
        });
    </script>
    <script type="text/javascript" src="{{ asset('js/jquery.maskMoney.js') }}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#harga_jasa').maskMoney();
        });
    </script>
<!-- //register -->
@endsection

resources/views/jasaku/testimonial.blade.php
@extends('layouts.layout')
@section('Title')
	Jasaku ID | Isi Testimonial
@endsection
@section('Content')
<!-- breadcrumbs -->
	<div class="breadcrumbs">
		<div class="container">
			<ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
				<li><a href="index.html"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Beranda</a></li>
				<li class="active">Testimonial</li>
			</ol>
		</div>
	</div>
<!-- //breadcrumbs -->
<!-- mail -->
	<form method="POST" action="{{ route('isi-testimonial.store') }}">
		{{ csrf_field() }}
		<div class="mail animated wow zoomIn" data-wow-delay=".5s">
		<div class="container">
			<h2 style="font-size: 48px;" class="mid">Isi Testimonial</h2>
			<hr>
			<p class="est">Isi testimonial setelah menyewa jasa bahwa <b>JasakuID</b> adalah market place yang menjanjikan. mohon kirimkan kritik dan saran dengan menggunakan format dibawah ini. Testimonial yang anda kirimkan akan membantu kami dalam pengembangan <b>JasakuID</b> dan juga membantu membuat jasa yang ada pada market place ini menjadi terpercaya. <br><br> <strong>Cek <a href="{{ url('/history-testimonial') }}" style="text-align: center;">disini</a> untuk melihat beberapa testimnonial.</strong></p>

			<div class="mail-grids">
				<div class="col-md-12 mail-grid-left animated wow slideInLeft" data-wow-delay=".5s">
					<div class="col-xs-12">
						<div class="form-group">
							<input type="text" id="nama" name="nama" required="" placeholder="Nama">
						</div>
					</div>
					<div class="col-xs-12">
						<div class="form-group">
							<input type="email" id="email" name="email" required="" placeholder="Email">		
						</div>
					</div>
					<div class="col-xs-12">
						<div class="form-group">
							<input type="text" id="alamat" name="alamat" required="" placeholder="Alamat Anda">
						</div>
					</div>
					<div class="col-xs-6">
						<div class="form-group">
							<select name="rating" id="rating" class="form-control" required placeholder="Rating">
                        		<option value="0.0" class="yes">0.0</option>
                        		<option value="1.0" class="yes">1.0</option>
                        		<option value="2.0" class="yes">2.0</option>
                        		<option value="3.0" class="yes">3.0</option>
                        		<option value="4.0" class="yes">4.0</option>
                        		<option value="5.0" class="yes">5.0</option>
                    		</select>		
						</div>
					</div>
					<div class="col-xs-12">
						<div class="form-group">
							<input type="text" id="judul_testi" name="judul_testi" required=""placeholder="Subject">		
						</div>
					</div>
					<div class="col-md-12">
						<div class="form-group">
							<textarea type="text" id="pesan_testi" name="pesan_testi" required="" placeholder="Pesan Anda"></textarea>	
						</div>
					</div>
					<div class="col-md-12">
						<div class="form-group">
							<input type="submit" value="Kirim Testimonial" >
						</div>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
		</div>
	</form>
<!-- //mail -->
@endsection