routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
/*Route::get('/',  function(){
	return view('index');
});*/
// Route::get('qr-code', function () 
// {
// 	$file = public_path('qr.png');
//   	return QRCode::text('thusa')->setOutfile($file)->png();    
// });
Route::get('history', 'HomeController@qrcode');
Route::get('/', 'PagesController@index');
Route::get('/index', 'PagesController@index')->name('index');
Route::resource('edit-profil', 'UsersController');
Route::resource('kategori-jasa', 'KategorisController');
Route::resource('tambah-jasa', 'TambahJasaController');
Route::resource('pembayaran-jasa', 'PembayaranController');
Route::resource('kontak-kami', 'KontakKamiController');
Route::resource('isi-testimonial', 'TestimonialController');
Route::get('/detail-jasa/{id}', 'PagesController@detailJasa')->name('detail-jasa');
Route::get('/keranjang-anda', 'PagesController@cart');
Route::get('/produk', 'PagesController@produk');
Route::get('search', 'PagesController@search');
Route::get('/hasilPencarian', 'PagesController@hasilPencarian');
Route::get('/checkout', 'PagesController@checkout');
Route::get('/pembayaran', 'PagesController@pembayaran');
Route::get('/bahasa-inggris', 'HomeController@bahasainggris');
Route::get('/biologi', 'HomeController@biologi');
Route::get('/dokumentasi-acara', 'HomeController@dokumentasiacara');
Route::get('/foto-pernikahan', 'HomeController@fotopernikahan');
Route::get('/foto-ulang-tahun', 'HomeController@fotoulangtahun');
Route::get('/furniture', 'HomeController@furniture');
Route::get('/matematika', 'HomeController@matematika');
Route::get('/mail', 'HomeController@mail');
Route::get('/editprofile', 'HomeController@editprofile');
Route::get('/cart/{id}', 'PagesController@AddToCart');
Route::get('/remove/{id}', 'PagesController@remove');
Route::get('/kontakkami', 'PagesController@kontakkami');
Route::get('/privacy-policy', 'PagesController@privacy');
Route::get('/verify/{token}', 'VerifyController@verify')->name('verify');

/** ADMIN */
Route::prefix('admin')->group(function() {
	Route::resource('dashboard', 'AdminsController');
	Route::resource('daftar-jasa', 'DaftarJasasController');
	Route::resource('daftar-user', 'DaftarUsersController');
	Route::resource('daftar-order', 'DaftarOrdersController');
	Route::resource('daftar-bukti-pembayaran', 'DaftarPembayaransController');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/layout-admin.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <title>@yield('Title')</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="{{ asset('vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{{ asset('vendor/metisMenu/metisMenu.min.css') }}" rel="stylesheet">

    <!-- DataTables CSS -->
    <link href="{{ asset('vendor/datatables-plugins/dataTables.bootstrap.css') }}" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="{{ asset('vendor/datatables-responsive/dataTables.responsive.cs') }}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{ asset('dist/css/sb-admin-2.css') }}" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="{{ asset('vendor/morrisjs/morris.css" rel="stylesheet') }}">

    <!-- Custom Fonts -->
    <link href="{{ asset('vendor/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">
    <link rel="icon" href="{{ asset('images/logo_tab.png') }}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <!-- Navigation -->
    @if(Auth::user())
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ route('dashboard.index') }}">Admin Jasakuid</a>
            </div>
            <!-- /.navbar-header -->
            <ul class="nav navbar-top-links navbar-right">
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <!-- KOSONGKAN SPACE -->
                        </li>
                        <li>
                            <a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="{{ route('daftar-jasa.index') }}"><i class="fa fa-comments fa-fw"></i>Daftar Jasa</a>
                        </li>
                        <li>
                            <a href="{{ route('daftar-user.index') }}"><i class="fa fa-tasks fa-fw"></i> Daftar User</a>
                        </li>
                        <li>
                            <a href="{{ route('daftar-order.index') }}"><i class="fa fa-shopping-cart fa-fw"></i> Daftar Order</a>
                        </li>
                        <li>
                            <a href="{{ route('daftar-bukti-pembayaran.index') }}"><i class="fa fa-support fa-fw"></i> Daftar Bukti Pembayaran</a>
                        </li>
                        <li>
                            <a href="{{ url('api/admin/get-daftar-jasa') }}"><i class="fa fa-shopping-cart fa-fw"></i> Daftar Pagination Jasa</a>
                        </li>
                        <li>
                            <a href="{{ url('api/admin/get-daftar-user') }}"><i class="fa fa-shopping-cart fa-fw"></i> Daftar Pagination User</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>
    @endif

    @yield('content-admin')
    <!-- jQuery -->
    <script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{ asset('vendor/bootstrap/js/bootstrap.min.js') }}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{{ asset('vendor/metisMenu/metisMenu.min.js') }}"></script>

    <!-- Morris Charts JavaScript -->
    <script src="{{ asset('vendor/raphael/raphael.min.js') }}"></script>
    <script src="{{ asset('vendor/morrisjs/morris.min.js') }}"></script>
    <script src="{{ asset('data/morris-data.js') }}"></script>

    <!-- DataTables JavaScript -->
    <script src="{{ asset('vendor/datatables/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables-plugins/dataTables.bootstrap.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables-responsive/dataTables.responsive.js') }}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{{ asset('/dist/js/sb-admin-2.js') }}"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
            responsive: true
        });
    });
    </script>
    <script>
        $('#myModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget)
            var id = button.data('id')
            var modal = $(this)
            
            modal.find('.modal-body #id').val(id);
        })
    </script>
</body>
</html>

resources/views/layouts/layout-editprofil.blade.php
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
<title>@yield('Title1')</title>
<!-- for-mobile-apps -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Best Store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //for-mobile-apps -->
<link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet" type="text/css" media="all" />
<link href="{{ asset('css/style.css') }}"  rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet" type="text/css" href="{{ asset('css/temp.css') }}">
<link rel="icon" href="{{ asset('images/logo_tab.png') }}">
<!-- js -->
<script src="{{ asset('js/jquery.min.js') }}"></script>
<script src="{{ asset('js/jquery-ui.min.js') }}"></script>
<script scr="{{ asset('js/jquery-1.12.4.js') }}"></script>
<script src="{{ asset('js/autocomplete.js') }}"></script>
<!-- //js -->
<!-- cart -->
<script src="{{ asset('js/simpleCart.min.js') }}"></script>
<!-- cart -->
<!-- for bootstrap working -->
<script type="text/javascript" src="{{ asset('js/bootstrap-3.1.1.min.js') }}"></script>
<!-- timer -->
<link rel="stylesheet" href="{{ asset('css/jquery.countdown.css') }}" />
<!-- //timer -->
<!-- animation-effect -->
<link href="{{ asset('css/animate.min.css') }}" rel="stylesheet"> 
<link rel="stylesheet" href="{{ asset('css/jquery-ui.css') }}">
<script src="{{ asset('js/wow.min.js') }}"></script>
<script>
 new WOW().init();
</script>
<!-- //animation-effect -->
</head>
	
<body>
<!-- header -->
	<div class="header">
		<div class="container">
			<div class="header-grid">
				<div class="header-grid-left animated wow slideInLeft" data-wow-delay=".5s">
					<ul>
						@if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    	@endif
						@guest
						<li><i class="glyphicon glyphicon-log-in" aria-hidden="true"></i><a href="{{ route('login') }}">Masuk</a></li>
						<li><i class="glyphicon glyphicon-book" aria-hidden="true"></i><a href="{{ route('register') }}">Daftar</a></li>
						@else
						<li><i class="glyphicon glyphicon-log-in" aria-hidden="true"></i><a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a></li>
						<form id="logout-form" action="{{ route('logout') }}" method="POST" class="none">
	                                    {{ csrf_field() }}
                        </form>
						<p class="alert alert-success"><a href="{{ url('edit-profil/'.Auth::user()->id.'/edit') }}">{{ Auth::user()->name }}</a></p>
	                    @endguest
					</ul>
				</div>
				<div class="header-grid-right animated wow slideInRight" data-wow-delay=".5s">
					@if(Auth::check())
					<ul class="hitam">
						<div class="simpleCart_shelfItem products-right-grid1-add-cart">
							<p><span class="#"></span><a class="#" href="{{ route('tambah-jasa.index') }}" style="color: black;">Tambah Jasa</a></p>
						</div>
					</ul>
					@endif
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="logo-nav">
				<div class="logo-nav-left animated wow zoomIn" data-wow-delay=".5s">
					<h1><a href="{{ url('/index') }}"><img src="{{ asset('images/logo.png') }}" alt=" " class="img-responsive" /></a></h1>
				</div>
		</div>
	</div>
<!-- //header -->
@yield('Content-Form')
<!-- footer -->
	<div class="footer">
		<div class="container">
			<div class="footer-grids">
				<div class="col-md-3 footer-grid animated wow slideInLeft" data-wow-delay=".5s">
					<h3>Tentang Kami</h3>
					<p>Kami adalah penyedia berbagai macam jasa sesuai kebutuhan anda</span></p>
				</div>
				<div class="col-md-3 footer-grid animated wow slideInLeft" data-wow-delay=".6s">
					<h3>Informasi Kontak</h3>
					<ul>
						<li><i class="glyphicon glyphicon-map-marker" aria-hidden="true"></i>Tenggilis Mejoyo, <span>Surabaya.</span></li>
						<li><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i><a href="mailto:info@example.com">jasakuid@gmail.com</a></li>
						<li><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i>081990102911</li>
					</ul>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="footer-logo animated wow slideInUp" data-wow-delay=".5s">
				<h2><a href="{{ url('/index') }}">Jasaku ID</a></h2>
				<ul class="social-icons">
						<li><a href="#" class="facebook"></a></li>
						<li><a href="#" class="twitter"></a></li>
						<li><a href="#" class="g"></a></li>
						<li><a href="#" class="instagram"></a></li>
					</ul>
			</div>
			<div class="copy-right animated wow slideInUp" data-wow-delay=".5s">
				<p>&copy 2018 Jasaku ID. All rights reserved | Design by Team E-Comm Ubaya</p>
			</div>
		</div>
	</div>
<!-- //footer -->
</body>
</html>

resources/views/layouts/layout.blade.php
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
<title>@yield('Title')</title>
<!-- for-mobile-apps -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Best Store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //for-mobile-apps -->
<link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet" type="text/css" media="all" />
<link href="{{ asset('css/style.css') }}"  rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet" type="text/css" href="{{ asset('css/temp.css') }}">
<link rel="icon" href="{{ asset('images/logo_tab.png') }}">
<!-- js -->
<script src="{{ asset('js/jquery.min.js') }}"></script>
<script src="{{ asset('js/jquery-ui.min.js') }}"></script>
<script scr="{{ asset('js/jquery-1.12.4.js') }}"></script>
<script src="{{ asset('js/autocomplete.js') }}"></script>
<script src="https://js.stripe.com/v3/"></script>
<!-- //js -->
<!-- cart -->
<script src="{{ asset('js/simpleCart.min.js') }}"></script>
<!-- cart -->
<!-- for bootstrap working -->
<script type="text/javascript" src="{{ asset('js/bootstrap-3.1.1.min.js') }}"></script>
<!-- timer -->
<link rel="stylesheet" href="{{ asset('css/jquery.countdown.css') }}" />
<link rel="stylesheet" href="{{ asset('css/test.css') }}" />
<!-- //timer -->
<!-- animation-effect -->
<link href="{{ asset('css/animate.min.css') }}" rel="stylesheet"> 
<link rel="stylesheet" href="{{ asset('css/jquery-ui.css') }}">
<script src="{{ asset('js/wow.min.js') }}"></script>
<script>
 new WOW().init();
</script>
<!-- //animation-effect -->
</head>
	
<body>
<!-- header -->
	<div class="header">
		<div class="container">
			<div class="header-grid">
				<div class="header-grid-left animated wow slideInLeft" data-wow-delay=".5s">
					<ul>
						@if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    	@endif
						@guest
						<li><i class="glyphicon glyphicon-log-in" aria-hidden="true"></i><a href="{{ route('login') }}">Masuk</a></li>
						<li><i class="glyphicon glyphicon-book" aria-hidden="true"></i><a href="{{ route('register') }}">Daftar</a></li>
						@else
						<li>
							<i class="glyphicon glyphicon-log-in" aria-hidden="true"></i><a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>
						</li>
						<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
	                                    {{ csrf_field() }}
                        </form>
						<p class="alert alert-success"><a href="{{ url('edit-profil/'.Auth::user()->id.'/edit') }}">{{ Auth::user()->name }}</a></p>
						@if(auth()->user()->verified() == true)
						<p class='alert alert-success'>Akun anda : Terverifikasi</p>
						@else
						<p class='alert alert-danger'>Akun anda : Belum terverifikasi</p>
						@endif
	                    @endguest
					</ul>
				</div>
				<div class="header-grid-right animated wow slideInRight" data-wow-delay=".5s">
					@if(Auth::check())
					<ul>
						<div class="simpleCart_shelfItem products-right-grid1-add-cart">
							<p><span class="#"></span><a class="#" href="{{ route('tambah-jasa.index') }}" style="color: black;">Tambah Jasa</a></p>
						</div>
					</ul>
					@endif
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="logo-nav">
				<div class="logo-nav-left animated wow zoomIn" data-wow-delay=".5s">
					<h1><a href="{{ url('/index') }}"><img src="{{ asset('images/logo.png') }}" alt=" " class="img-responsive" /></a></h1>
				</div>
				<div class="logo-nav-left1">
					<nav class="navbar navbar-default">
						<div class="navbar-header nav_2">
							<button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>					
						</div>
						<div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
							<ul class="nav navbar-nav">
								<li class="active"><a href="{{ url('/index') }}" class="act">Beranda</a></li>	
								<!-- Mega Menu -->
								<li class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown">Kategori Jasa <b class="caret"></b></a>
									<ul class="dropdown-menu multi-column columns-3">
										<div class="row">
											@foreach($kategori as $kategoris)
											<div class="col-sm-6">
												<ul class="multi-column-dropdown">
													<!-- Nama Kategori - SEPTIANO -->
													<h6><a href="{{ url('kategori-jasa/'.$kategoris->nama_kategori_jasa) }}">{{ $kategoris->nama_kategori_jasa}}</a></h6>

													<!-- Nama Jasa - SEPTIANO -->
													@foreach($jasasaya as $jasa)
													@if($jasa->kategori_id == $kategoris->id)
													<li><a href="{{ url('detail-jasa/'.$jasa->nama_jasa) }}">{{$jasa->nama_jasa}}</a></li>
													@endif
													@endforeach
												</ul>
											</div>
											@endforeach
											<div class="clearfix"></div>
										</div>
									</ul>
								</li>
								<li><a href="{{url('/kontakkami')}}">Kontak Kami</a></li>
								<li class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown">Keranjang Anda<b class="caret"></b>
										@if(Session::has('cart'))
										<span class="badge">{{ Session::has('cart') ? Session::get('cart')->totalQty : '' }} item</span>
										
										@else
										<span class="badge">{{ Session::has('cart') ? Session::get('cart')->totalQty : '' }} 0 item</span>
										@endif
									</a>
									<ul class="dropdown-menu multi-column columns-2	clearfix">
										<div class="row">
											<div class="col-sm-6">
												<ul class="multi-column-dropdown" style="size: width: 40px; height: 40px;">
													<li><a href="{{ url('/keranjang-anda') }}">Pergi ke Keranjang</a></li>
													<li><a href="{{ url('/checkout') }}">Checkout</a></li>
												</ul>
											</div>
											<div class="clearfix"></div>
										</div>
									</ul>
								</li>
								<li><a href="{{url('/history')}}">Riwayat</a></li>
							</ul>
						</div>
					</nav>
				</div>
				<div class="container">
					<div class="row">
						<form action="{{ url('/hasilPencarian') }}" method="GET">
							<div id="custom-search-input">
	                            <div class="input-group col-md-12">
	                                <input type="text" class="form-control" name="searchrow" id="searchrow" placeholder="Cari Jasa" value="{{ isset($s) ? $s : '' }}"/>
	                                <span class="input-group-btn">
	                                    <button class="btn btn-danger" type="submit">
	                                        <span class=" glyphicon glyphicon-search"></span>
	                                    </button>
	                                </span>
	                            </div>
	                        </div>
						</form>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
<!-- //header -->
@yield('Content')
<!-- footer -->
	<div class="footer">
		<div class="container">
			<div class="footer-grids">
				<div class="col-md-3 footer-grid animated wow slideInLeft" data-wow-delay=".5s">
					<h3>Tentang Kami</h3>
					<p>Kami adalah penyedia berbagai macam jasa sesuai kebutuhan anda</span></p>
				</div>
				<div class="col-md-3 footer-grid animated wow slideInLeft" data-wow-delay=".6s">
					<h3>Informasi Kontak</h3>
					<ul>
						<li><i class="glyphicon glyphicon-map-marker" aria-hidden="true"></i>Tenggilis Mejoyo, <span>Surabaya.</span></li>
						<li><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i><a href="mailto:info@example.com">jasakuid@gmail.com</a></li>
						<li><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i>081990102911</li>
					</ul>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="footer-logo animated wow slideInUp" data-wow-delay=".5s">
				<h2><a href="{{ url('/index') }}">Jasaku ID</a></h2>
					<ul class="social-icons">
						<li><a href="#" class="facebook"></a></li>
						<li><a href="#" class="twitter"></a></li>
						<li><a href="#" class="g"></a></li>
						<li><a href="#" class="instagram"></a></li>
					</ul>
			</div>
			<div class="copy-right animated wow slideInUp" data-wow-delay=".5s">
				<p>&copy 2018 Jasaku ID. All rights reserved | Design by Team E-Comm Ubaya</p>
			</div>
		</div>
	</div>
<!-- //footer -->
</body>
</html>
<script type="text/javascript" src="{{ asset('js/checkout.js') }}"></script>